[project]
name = "www-site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.1"
dependencies = [
    "pelican[markdown]>=4.10.2",
    "setuptools>=75.3.0",
]
